name: C Workflow

on:
    push:
        branches:
        - master
      pull_request:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
        - name: Make the code accessible to the current workflow
          uses: actions/checkout@v2

        - name: Build
          run: |
            make
    test:
        needs: build

        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: Make the code accessible to the current workflow
            uses: actions/checkout@v2

            - name: Test the build
              run: |
                make test

