name: C Workflow

on: [ push ]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
        - name: make the code accessible to the current workflow
          uses: actions/checkout@v2

        - name: build
          run: |
            make
    test:
        needs: build

        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: make the code accessible to the current workflow
            uses: actions/checkout@v2

            - name: test the build
              run: |
                make test

