name: C Workflow

on: [push, pull_request]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
        - name: make the code accessible to the workflow
          uses: actions/checkout@v2

        - name: build
          run: |
            make
    test:
        needs: build

        name: Test
        runs-on: ubuntu-latest

        steps:
            - name: test
              run: |
                make test

